version: '3.4'

networks:
  jenkins_net:

secrets:
  jenkinsUser:
    external: true
  jenkinsPassword:
    external: true
  jenkinsSwarm:
    external: true

services:
  jenkins-master:
    hostname: jenkins-master
    image: joncatlin/jenkins-swarm-master
    volumes:
      - /mount/VM-File-Storage/jenkins-master:/var/jenkins_home
    ports:
      - "8080:8080"
    networks:
      - jenkins_net
    secrets:
      - source: jenkinsUser
        target: jenkinsUser
        uid: '1000'
        mode: 0440
      - source: jenkinsPassword
        target: jenkinsPassword
        uid: '1000'
        mode: 0440

  jenkins-slave:
    hostname: jenkins-slave
    image: joncatlin/jenkins-swarm-slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
    secrets:
      - source: jenkinsSwarm
        target: jenkinsSwarm
        mode: 0440
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s



